GNUSTEP_MAKEFILES = /usr/local/share/GNUstep/Makefiles/

include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = app 

#app_HEADER_FILES = src/AppController/AppController.h

app_OBJC_FILES = main.m

include $(GNUSTEP_MAKEFILES)/tool.make
